version: "3.0"
services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    # The Command will make redis-server run with our custom Configuration
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data #Used for persisting data
      - ./redis/conf:/usr/local/etc/redis #Used for configuring redis
    networks:
      - data_sharing

networks:
  data_sharing:
    driver: bridge